name: data_modeling_filtering
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  json_model: ^1.0.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  http: ^0.13.5

dev_dependencies: 
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

